[package]
name = "if_os"
version = "0.1.0"
authors = ["José Gilberto <medeiros.gilberto.br@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rlibc = "1.0.0"
bootloader = "0.9.8"